version: '2'
services:
  web:
    image: prooph/php:7.1-cli
    command: php -S 0.0.0.0:80 -t /app/public /app/public/index.php
    ports:
      - "8083:80"
    depends_on:
      - mongo
    volumes:
        - ./:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
